# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import helpful.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Object ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('group', models.CharField(blank=True, max_length=64, verbose_name='Group media')),
                ('file', models.FileField(upload_to=helpful.fields.upload_to, verbose_name='File')),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='dateCreated')),
                ('order', models.PositiveSmallIntegerField(default=500, verbose_name='Sort ordering')),
                ('downloads', models.PositiveIntegerField(default=0, editable=False, verbose_name='Downloads')),
                ('public', models.BooleanField(default=True, verbose_name='Public')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Content Type')),
            ],
            options={
                'ordering': ['created_at'],
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
    ]
