# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('key', models.SlugField(unique=True, verbose_name='key')),
            ],
        ),
        migrations.CreateModel(
            name='FileProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=2048, verbose_name='Value')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.FileKey', verbose_name='Key')),
            ],
        ),
    ]
