# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_filekey_fileproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileproperty',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.File', related_name='properties', verbose_name='File'),
        ),
    ]
